spring:
  kafka:
   consumer:
    bootstrap-servers: localhost:9092
    group-id: "my_group_id" 
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  
   producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer   
  datasource:
    platform: =h2
    url: jdbc:h2:mem:emp
  h2:
    console:
      enabled: true
